#!/usr/bin/env bash

set -exu

git config --global user.email "${GIT_USER_EMAIL}"
git config --global user.name "${GIT_USER_NAME}"

GOLANG_RELEASE="$(pwd)/${GOLANG_DIR}"

function make_private_yaml {
  cat > config/private.yml <<EOF
---
blobstore:
  options:
    access_key_id: ${BLOBSTORE_ACCESS_KEY_ID}
    secret_access_key: ${BLOBSTORE_SECRET_ACCESS_KEY}
EOF
}

function commit_if_changed {
  pushd ${GOLANG_RELEASE}
    GOLANG_RELEASE_TAG=$(git describe --abbrev=0 --tags)
  popd

  if [[ -n "$(git status -s)" ]]; then
    git commit -m "bump golang release to ${GOLANG_RELEASE_TAG}"
  fi
}

pushd ${RELEASE_DIR}
  make_private_yaml

  bosh vendor-package golang-1-linux ${GOLANG_RELEASE}
  git add .final_builds/packages/golang-1-linux/index.yml
  git add packages/golang-1-linux/spec.lock

  git checkout .
  commit_if_changed
popd

cp -a ${RELEASE_DIR}/. output-repo
