#!/usr/bin/env bash

set -exu

git config --global user.email "${GIT_USER_EMAIL}"
git config --global user.name "${GIT_USER_NAME}"

GOLANG_RELEASE="$(pwd)/${GOLANG_DIR}"

pushd ${RELEASE_DIR}
  cat > config/dev.yml <<EOF
---
dev_name: ${RELEASE_NAME}
EOF

  cat > config/private.yml <<EOF
---
blobstore:
  options:
    access_key_id: ${BLOBSTORE_ACCESS_KEY_ID}
    secret_access_key: ${BLOBSTORE_SECRET_ACCESS_KEY}
EOF

  bosh vendor-package golang-1-linux ${GOLANG_RELEASE}
  git add .final_builds/packages/golang-1-linux/index.yml
  git add packages/golang-1-linux/spec.lock

  git checkout .
  if [[ -n "$(git status -s)" ]]; then
    git commit -m "bump golang release"
  fi
popd

cp -a release/. output-repo
