#!/usr/bin/env bash
set -exu
export DEPLOYMENTS="$PWD/deployments"
export DEBIAN_FRONTEND=noninteractive
apt-get -y -qq update
apt-get -y -qq install expect
fly -t superpipe login -k -n $TEAM_NAME \
  -c https://concourse.superpipe.gcp.pcf-metrics.com \
  -u $USER \
  -p $PASSWORD
fly -t superpipe sync
$(dirname $0)/check-pipeline-deployment.exp
