#!/usr/bin/env bash
set -exu

export PATH="$PATH:$PWD"

export DEBIAN_FRONTEND=noninteractive
apt-get -y -qq update && apt-get -y -qq install expect

curl -o fly -L ${CONCOURSE_URL}/api/v1/cli?arch=amd64&platform=linux
chmod +x fly

fly -t ${FLY_TARGET} login -n ${TEAM_NAME} \
  -c ${CONCOURSE_URL} \
  -u ${USER} \
  -p ${PASSWORD}
fly -t ${FLY_TARGET} sync

EXPECT_SCRIPT=./deployments/${FLY_SCRIPT} $(dirname $0)/check-pipeline-deployment.exp
