#!/bin/bash
set -euxo pipefail

postfacto_login_response=$(curl -f "${POSTFACTO_API_URL}/login" \
  --request PUT \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data-binary "{\"retro\":{\"password\":\"${POSTFACTO_PASSWORD}\"}}")

postfacto_token=$(echo ${postfacto_login_response} | jq -r .token)
postfacto_response=$(curl -f "${POSTFACTO_API_URL}" \
  -H "authorization: Bearer ${postfacto_token}")

action_items_text=$(echo ${postfacto_response} | \
    jq '
      .retro.action_items
      | map(select(.done == false))
      | sort_by(.created_at)
      | map(.created_at = (.created_at | sub("\\.\\d{3}Z$"; "Z") | fromdateiso8601 | strftime("%m/%d")))
      | map("• " + .description + " [" + .created_at + "]")
      | join("\n")
    '
)

cat >> alert/attachments << EOF
[
  {
    "title": "Action Items from $(basename ${POSTFACTO_RETRO_URL}) Retro",
    "title_link": "${POSTFACTO_RETRO_URL}",
    "text": ${action_items_text}
  }
]
EOF
