#!/bin/bash
set -ex
source concourse-tasks/helpers/git.sh

mkdir -p $HOME/.ssh
ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts

pushd submodule-repo
  target_sha="$(git rev-parse HEAD)"
  submodule_repo_dir=${PWD}
popd

function fetch_submodules() {
  local parent_dir=$1
  pushd ${parent_dir}
    for submodule_path in $(git submodule | awk '{print $2}'); do
      pushd ${submodule_path}
        git fetch ${parent_dir}/${submodule_path}
        git checkout FETCH_HEAD
        fetch_submodules ${parent_dir}/${submodule_path}
      popd
    done
  popd
}

pushd "release-repo/$SUBMODULE_PATH"
  git fetch ${submodule_repo_dir}
  git checkout "$target_sha"
  submodule_name=$(basename $(git rev-parse --show-toplevel))
  fetch_submodules ${submodule_repo_dir}
popd

git_commit_all release-repo "Bump ${submodule_name} submodule"
cp -r release-repo/. bumped-release-repo/