#!/bin/bash
set -ex
source concourse-tasks/helpers/git.sh

mkdir -p $HOME/.ssh
ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts

pushd submodule-repo
  target_sha="$(git rev-parse HEAD)"
  submodule_repo_dir=${PWD}
popd

pushd "release-repo/$SUBMODULE_PATH"
  git fetch ${submodule_repo_dir}
  git checkout "$target_sha"
  submodule_name=$(basename $(git rev-parse --show-toplevel))
popd

git_commit_all release-repo "Bump ${submodule_name} submodule"
cp -r release-repo/. bumped-release-repo/