#!/bin/bash
set -ex
source concourse-tasks/helpers/git.sh

mkdir -p $HOME/.ssh
ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts

pushd submodule-repo
  target_sha="$(git rev-parse HEAD)"
  submodule_last_commit=$(git log ${target_sha} --pretty=format:'%h %an: %s' -n 1)
  submodule_repo_dir=${PWD}
popd

function fetch_submodules() {
  local fetch_from_dir=$1
  for submodule_path in $(git submodule | awk '{print $2}'); do
    pushd ${submodule_path}
      git init --quiet
      git fetch ${fetch_from_dir}/${submodule_path}
      git checkout FETCH_HEAD
      fetch_submodules ${fetch_from_dir}/${submodule_path}
    popd
  done
}

pushd "release-repo/$SUBMODULE_PATH"
  git fetch ${submodule_repo_dir}
  git checkout "$target_sha"
  submodule_name=$(basename $(git rev-parse --show-toplevel))
  fetch_submodules ${submodule_repo_dir}
  git clean -ffd
popd

git_commit_all release-repo "${COMMIT_MESSAGE:-Bump ${submodule_name} submodule to SHA: ${target_sha}

            ${submodule_last_commit}}"
cp -r release-repo/. bumped-release-repo/
